GENERAL:
  EXP_NAME: ReAct-30-10-d256x4-t300
  CHECKPOINT: ./checkpoints
  LOG_DIR: ./log

TRAIN:
  LR: 1e-4
  WEIGHT_DECAY: 0.00002
  BATCH_SIZE: 512
  EPOCH: 4000
  STEP: 1000000
  LOG_STEPS: 50
  SAVE_STEPS: 20000
  SAVE_EPOCH: 250
  SAVE_TOP_K: -1
  RESUME: #checkpoints/IG-S/8/model/epoch=99-step=17600.ckpt
  NUM_WORKERS: 10
  MODE: finetune
  LAST_EPOCH: 0
  LAST_ITER: 0
  HISTORY_LENGTH: 30
  PREDICT_LENGTH: 10
