NAME: InterGen
NUM_LAYERS: 3
NUM_HEADS: 8
DROPOUT: 0.1
# INPUT_DIM: 60  # 48+12=60, 48+2=50
# INPUT_DIM: 50  # 6*6=36, 36+12=48, 36+2=38(2=2*num_obj)

HUMAN_BODY_DIM: 36
HAND_DIM: 12
ADD_OCCUPANCY: True
NO_HUMAN_MOTION: False
HISTORY_LENGTH: 30
REMOVE_HISTORY: 0
PREDICT_LENGTH: 0
# INPUT_DIM = HUMAN_BODY_DIM + HAND_DIM + 2 * NUM_OBJ
HD_INPUT:
  - "hand_pos"
  - "hand_imgs"
  - "hand_near"

OBJ_MASK_RATIO: 0.0
BETTER_STATE: False
HAND_IOU_MEAN_POOL: False
HAND_POS_NOISE_STD: 0.

NUM_CLASS: 14
LATENT_DIM: 128
FF_SIZE: 128
SKIP_TEXT: True
NUM_OBJ: 5
ACTIVATION: gelu

DIFFUSION_STEPS: 300
BETA_SCHEDULER: cosine
SAMPLER: uniform

MOTION_REP: global
FINETUNE: False

TEXT_ENCODER: clip
T_BAR: 210

CONTROL: text
STRATEGY: ddim20
CFG_WEIGHT: 1

